// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(name, sellIn, quality) {
  return {
          name: name,
          sellIn: sellIn,
          quality: quality
        };
}

var Item = {
  make: make
};

function upTo50(__x) {
  return Math.min(50, __x);
}

function min0(__x) {
  return Math.max(0, __x);
}

function updateQuality(items) {
  return items.map(function (item) {
              var match = item.name;
              switch (match) {
                case "Aged Brie" :
                    return {
                            name: item.name,
                            sellIn: item.sellIn - 1 | 0,
                            quality: Math.min(50, item.quality + 1 | 0)
                          };
                case "Backstage passes to a TAFKAL80ETC concert" :
                    var match$1 = item.sellIn;
                    var match$2 = item.quality;
                    return {
                            name: item.name,
                            sellIn: item.sellIn - 1 | 0,
                            quality: match$2 !== 50 ? (
                                match$1 !== 0 ? (
                                    match$1 <= 5 ? Math.min(50, match$2 + 3 | 0) : (
                                        match$1 <= 10 ? Math.min(50, match$2 + 2 | 0) : Math.min(50, match$2 + 1 | 0)
                                      )
                                  ) : 0
                              ) : 50
                          };
                case "Sulfuras, Hand of Ragnaros" :
                    return item;
                default:
                  var match$3 = item.sellIn;
                  var match$4 = item.quality;
                  return {
                          name: item.name,
                          sellIn: item.sellIn - 1 | 0,
                          quality: match$3 !== 0 ? Math.max(0, match$4 - 1 | 0) : item.quality - 2 | 0
                        };
              }
            });
}

exports.Item = Item;
exports.upTo50 = upTo50;
exports.min0 = min0;
exports.updateQuality = updateQuality;
/* No side effect */
