// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/rescript-jest/src/jest.bs.js");
var GildedRose = require("./GildedRose.bs.js");

Jest.describe("Gilded Rose", (function (param) {
        Jest.test("quality cannot be lower than 0", (function (param) {
                return Jest.Expect.toEqual(Jest.Expect.expect(GildedRose.updateQuality([{
                                      name: "Whatever",
                                      sellIn: 1,
                                      quality: 0
                                    }])), [{
                              name: "Whatever",
                              sellIn: 0,
                              quality: 0
                            }]);
              }));
        Jest.test("after sellIn expires quality degrades twice as fast", (function (param) {
                return Jest.Expect.toEqual(Jest.Expect.expect(GildedRose.updateQuality([{
                                      name: "Whatever",
                                      sellIn: 0,
                                      quality: 10
                                    }])), [{
                              name: "Whatever",
                              sellIn: -1,
                              quality: 8
                            }]);
              }));
        Jest.test("Aged Brie's quality increases as the days go by", (function (param) {
                return Jest.Expect.toEqual(Jest.Expect.expect(GildedRose.updateQuality([{
                                      name: "Aged Brie",
                                      sellIn: 1,
                                      quality: 10
                                    }])), [{
                              name: "Aged Brie",
                              sellIn: 0,
                              quality: 11
                            }]);
              }));
        Jest.test("Sulfuras quality is 80 and it never changes", (function (param) {
                return Jest.Expect.toEqual(Jest.Expect.expect(GildedRose.updateQuality([{
                                      name: "Sulfuras, Hand of Ragnaros",
                                      sellIn: 1,
                                      quality: 80
                                    }])), [{
                              name: "Sulfuras, Hand of Ragnaros",
                              sellIn: 1,
                              quality: 80
                            }]);
              }));
        Jest.describe("Backstage passes", (function (param) {
                Jest.test("quality drops to 0 after sellIn expires", (function (param) {
                        return Jest.Expect.toEqual(Jest.Expect.expect(GildedRose.updateQuality([{
                                              name: "Backstage passes to a TAFKAL80ETC concert",
                                              sellIn: 0,
                                              quality: 10
                                            }])), [{
                                      name: "Backstage passes to a TAFKAL80ETC concert",
                                      sellIn: -1,
                                      quality: 0
                                    }]);
                      }));
                Jest.test("quality increases by 1 when sellIn is more than 10", (function (param) {
                        return Jest.Expect.toEqual(Jest.Expect.expect(GildedRose.updateQuality([{
                                              name: "Backstage passes to a TAFKAL80ETC concert",
                                              sellIn: 11,
                                              quality: 10
                                            }])), [{
                                      name: "Backstage passes to a TAFKAL80ETC concert",
                                      sellIn: 10,
                                      quality: 11
                                    }]);
                      }));
                Jest.test("quality increases by 2 if 5 < sellIn <= 10", (function (param) {
                        return Jest.Expect.toEqual(Jest.Expect.expect(GildedRose.updateQuality([{
                                              name: "Backstage passes to a TAFKAL80ETC concert",
                                              sellIn: 10,
                                              quality: 10
                                            }])), [{
                                      name: "Backstage passes to a TAFKAL80ETC concert",
                                      sellIn: 9,
                                      quality: 12
                                    }]);
                      }));
              }));
      }));

/*  Not a pure module */
