// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(name, sellIn, quality) {
  return {
          name: name,
          sellIn: sellIn,
          quality: quality
        };
}

var Item = {
  make: make
};

function upTo50(__x) {
  return Math.min(50, __x);
}

function min0(__x) {
  return Math.max(0, __x);
}

function updateQuality(items) {
  return items.map(function (item) {
              var newItem = item;
              var match = newItem.name;
              switch (match) {
                case "Aged Brie" :
                    var init = newItem;
                    newItem = {
                      name: init.name,
                      sellIn: newItem.sellIn - 1 | 0,
                      quality: Math.min(50, newItem.quality + 1 | 0)
                    };
                    break;
                case "Backstage passes to a TAFKAL80ETC concert" :
                    var init$1 = newItem;
                    var match$1 = newItem.sellIn;
                    var match$2 = newItem.quality;
                    newItem = {
                      name: init$1.name,
                      sellIn: newItem.sellIn - 1 | 0,
                      quality: match$2 !== 50 ? (
                          match$1 !== 0 ? (
                              match$1 <= 5 ? Math.min(50, match$2 + 3 | 0) : (
                                  match$1 <= 10 ? Math.min(50, match$2 + 2 | 0) : Math.min(50, match$2 + 1 | 0)
                                )
                            ) : 0
                        ) : 50
                    };
                    break;
                case "Sulfuras, Hand of Ragnaros" :
                    newItem = newItem;
                    break;
                default:
                  var init$2 = newItem;
                  var match$3 = newItem.sellIn;
                  var match$4 = newItem.quality;
                  newItem = {
                    name: init$2.name,
                    sellIn: newItem.sellIn - 1 | 0,
                    quality: match$3 !== 0 ? Math.max(0, match$4 - 1 | 0) : newItem.quality - 2 | 0
                  };
              }
              return newItem;
            });
}

exports.Item = Item;
exports.upTo50 = upTo50;
exports.min0 = min0;
exports.updateQuality = updateQuality;
/* No side effect */
