// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/rescript-jest/src/jest.bs.js");
var GildedRose = require("./GildedRose.bs.js");

Jest.describe("Gilded Rose", (function (param) {
        Jest.test("quality cannot be lower than 0", (function (param) {
                return Jest.Expect.toEqual(Jest.Expect.expect(GildedRose.updateQuality([{
                                      name: "Whatever",
                                      sellIn: 1,
                                      quality: 0
                                    }])), [{
                              name: "Whatever",
                              sellIn: 0,
                              quality: 0
                            }]);
              }));
        Jest.test("after sellIn expires quality degrades twice as fast", (function (param) {
                return Jest.Expect.toEqual(Jest.Expect.expect(GildedRose.updateQuality([{
                                      name: "Whatever",
                                      sellIn: 0,
                                      quality: 10
                                    }])), [{
                              name: "Whatever",
                              sellIn: -1,
                              quality: 8
                            }]);
              }));
      }));

/*  Not a pure module */
